DROP TABLE shidx_t1;

CREATE TABLE shidx_t1(KEY STRING, VALUE STRING);

CREATE INDEX idx_t1 ON TABLE shidx_t1(KEY) AS "COMPACT" WITH DEFERRED REBUILD;
ALTER INDEX idx_t1 ON shidx_t1 REBUILD;

EXPLAIN
SHOW INDEX ON shidx_t1;

SHOW INDEX ON shidx_t1;

EXPLAIN
SHOW INDEXES ON shidx_t1;

SHOW INDEXES ON shidx_t1;

DROP TABLE shidx_t1;
